"""
Controller para gerenciamento de cookies do Instagram
"""
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from pydantic import BaseModel
from typing import List, Dict, Any
from app.Providers.DatabaseServiceProvider import get_db
from app.Http.Middleware.AuthMiddleware import get_current_admin_user
from app.domain.entities.user import User
from config import settings
import os
import logging

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/cookies", tags=["Cookies"])


class CookieItem(BaseModel):
    """Item de cookie individual"""
    domain: str
    expirationDate: float = None
    hostOnly: bool = False
    httpOnly: bool = False
    name: str
    path: str = "/"
    sameSite: str = "unspecified"
    secure: bool = True
    session: bool = False
    value: str


class UpdateCookiesRequest(BaseModel):
    """Request para atualizar cookies"""
    cookie_string: List[CookieItem]


def convert_cookies_to_netscape(cookies: List[CookieItem]) -> str:
    """
    Converte lista de cookies JSON para formato Netscape (yt-dlp)
    
    Formato Netscape:
    domain	flag	path	secure	expiration	name	value
    """
    lines = [
        "# Netscape HTTP Cookie File",
        "# This file is generated by the API. Do not edit manually.",
        ""
    ]
    
    for cookie in cookies:
        # Domain
        domain = cookie.domain
        
        # Flag: TRUE se não for hostOnly, FALSE se for
        flag = "FALSE" if cookie.hostOnly else "TRUE"
        
        # Path
        path = cookie.path if cookie.path else "/"
        
        # Secure: TRUE ou FALSE
        secure = "TRUE" if cookie.secure else "FALSE"
        
        # Expiration: timestamp Unix (0 se for session cookie)
        if cookie.session or cookie.expirationDate is None:
            expiration = "0"
        else:
            # Converte para timestamp Unix (já está em segundos)
            expiration = str(int(cookie.expirationDate))
        
        # Name e Value
        name = cookie.name
        value = cookie.value
        
        # Monta linha no formato Netscape
        line = f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}"
        lines.append(line)
    
    return "\n".join(lines)


@router.post("/update", status_code=status.HTTP_200_OK)
def update_cookies(
    request: UpdateCookiesRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_admin_user)
):
    """
    Atualiza cookies do Instagram
    
    Aceita lista de cookies no formato JSON e converte para formato Netscape
    usado pelo yt-dlp.
    """
    try:
        # Valida cookies
        if not request.cookie_string or len(request.cookie_string) == 0:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Lista de cookies não pode estar vazia"
            )
        
        # Converte para formato Netscape
        netscape_content = convert_cookies_to_netscape(request.cookie_string)
        
        # Garante que o diretório existe
        cookie_dir = os.path.dirname(settings.SESSION_FILE_PATH)
        os.makedirs(cookie_dir, exist_ok=True)
        
        # Salva arquivo
        with open(settings.SESSION_FILE_PATH, 'w', encoding='utf-8') as f:
            f.write(netscape_content)
        
        logger.info(f"Cookies atualizados por usuário {current_user.id} ({current_user.username})")
        
        return {
            "ok": True,
            "message": "Cookies atualizados com sucesso",
            "cookies_count": len(request.cookie_string),
            "file_path": settings.SESSION_FILE_PATH
        }
    
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Erro ao atualizar cookies: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Erro ao atualizar cookies: {str(e)}"
        )


@router.get("/status", status_code=status.HTTP_200_OK)
def get_cookies_status(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_admin_user)
):
    """
    Verifica status dos cookies (se arquivo existe e quantos cookies tem)
    """
    try:
        cookie_file = settings.SESSION_FILE_PATH
        exists = os.path.exists(cookie_file)
        
        cookies_count = 0
        if exists:
            with open(cookie_file, 'r', encoding='utf-8') as f:
                lines = f.readlines()
                # Conta linhas que não são comentários e não estão vazias
                cookies_count = len([
                    line for line in lines 
                    if line.strip() and not line.strip().startswith('#')
                ])
        
        return {
            "exists": exists,
            "file_path": cookie_file,
            "cookies_count": cookies_count
        }
    
    except Exception as e:
        logger.error(f"Erro ao verificar status dos cookies: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Erro ao verificar status: {str(e)}"
        )

